//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public int Folder_ID { get; set; }
        public int FounderID { get; set; }
        public string Folder_Name { get; set; }
        public int FatherFolderID { get; set; }
        public int DeleteState { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public System.DateTime EstablishTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual User User { get; set; }
    }
}
