//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend_Conversation
    {
        public Friend_Conversation()
        {
            this.FriendFile_Library = new HashSet<FriendFile_Library>();
        }
    
        public int Conversation_ID { get; set; }
        public int Sender { get; set; }
        public int Receiver { get; set; }
        public string Count { get; set; }
        public System.DateTime Conversation_data { get; set; }
        public int Conversation_type { get; set; }
        public int DeleteShare { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<FriendFile_Library> FriendFile_Library { get; set; }
    }
}
