//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Friend_ID { get; set; }
        public int User_ID { get; set; }
        public int Friend_User_ID { get; set; }
        public int Blacklist { get; set; }
        public System.DateTime SendOut { get; set; }
        public int Adopt { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
    }
}
