//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendFile_Details
    {
        public int FriendFile_DetailsID { get; set; }
        public int FriendFile_LibraryID { get; set; }
        public string FilePath { get; set; }
    
        public virtual FriendFile_Library FriendFile_Library { get; set; }
    }
}
