//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Group_Conversation = new HashSet<Group_Conversation>();
            this.Group_personnel = new HashSet<Group_personnel>();
        }
    
        public int Group_ID { get; set; }
        public string Group_Name { get; set; }
        public string Group_link { get; set; }
        public int Group_Number { get; set; }
        public int Founder { get; set; }
        public System.DateTime EstablishTime { get; set; }
    
        public virtual ICollection<Group_Conversation> Group_Conversation { get; set; }
        public virtual ICollection<Group_personnel> Group_personnel { get; set; }
        public virtual User User { get; set; }
    }
}
