//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupFile_Library
    {
        public GroupFile_Library()
        {
            this.GroupFile_Details = new HashSet<GroupFile_Details>();
        }
    
        public int GroupFile_LibraryID { get; set; }
        public int Conversation_ID { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public int Contain { get; set; }
    
        public virtual Group_Conversation Group_Conversation { get; set; }
        public virtual ICollection<GroupFile_Details> GroupFile_Details { get; set; }
    }
}
