//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaiduSkyDriveEntities : DbContext
    {
        public BaiduSkyDriveEntities()
            : base("name=BaiduSkyDriveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Friend_Conversation> Friend_Conversation { get; set; }
        public virtual DbSet<FriendFile_Details> FriendFile_Details { get; set; }
        public virtual DbSet<FriendFile_Library> FriendFile_Library { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Conversation> Group_Conversation { get; set; }
        public virtual DbSet<Group_personnel> Group_personnel { get; set; }
        public virtual DbSet<GroupFile_Details> GroupFile_Details { get; set; }
        public virtual DbSet<GroupFile_Library> GroupFile_Library { get; set; }
        public virtual DbSet<Personal_data> Personal_data { get; set; }
        public virtual DbSet<Share_data> Share_data { get; set; }
        public virtual DbSet<Skin> Skins { get; set; }
        public virtual DbSet<Store_data> Store_data { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
