//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_data
    {
        public int Personal_dataID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Blood_type { get; set; }
        public string PlaceBirth { get; set; }
        public string PlaceResidence { get; set; }
    
        public virtual User User { get; set; }
    }
}
